/*
 The commands dictionary below is indexed by the command numbers as interpreted by the billboard hardware
 the properties are as followed:
 desc - a text description for used in the UI
 player - determines if the command controls the Player 1 or Player 2 billboard (null for both players)
 type - determine if the command controls a characters, display segment, display dots, winner lamps, or animation
 pswap - the corrosponding command number to convert the command from p1 to p2 or visa-versa
 mirror (only on player: null commands) - the corrosponding command number for duplicating p1 output on p2 and visa-versa
 sswap (only on type: char and seg) - the corrosponding command number for swapping output on the left and right digits
*/
var commands = {};
commands[0] = {desc: 'P1 Right Digit "0"', player: 1, type: 'char', pswap: 64, sswap: 32};
commands[1] = {desc: 'P1 Right Digit "1"', player: 1, type: 'char', pswap: 65, sswap: 33};
commands[2] = {desc: 'P1 Right Digit "2"', player: 1, type: 'char', pswap: 66, sswap: 34};
commands[3] = {desc: 'P1 Right Digit "3"', player: 1, type: 'char', pswap: 67, sswap: 35};
commands[4] = {desc: 'P1 Right Digit "4"', player: 1, type: 'char', pswap: 68, sswap: 36};
commands[5] = {desc: 'P1 Right Digit "5"', player: 1, type: 'char', pswap: 69, sswap: 37};
commands[6] = {desc: 'P1 Right Digit "6"', player: 1, type: 'char', pswap: 70, sswap: 38};
commands[7] = {desc: 'P1 Right Digit "7"', player: 1, type: 'char', pswap: 71, sswap: 39};
commands[8] = {desc: 'P1 Right Digit "8"', player: 1, type: 'char', pswap: 72, sswap: 40};
commands[9] = {desc: 'P1 Right Digit "9"', player: 1, type: 'char', pswap: 73, sswap: 41};
commands[10] = {desc: 'P1 Right Digit "A"', player: 1, type: 'char', pswap: 74, sswap: 42};
commands[11] = {desc: 'P1 Right Digit "b"', player: 1, type: 'char', pswap: 75, sswap: 43};
commands[12] = {desc: 'P1 Right Digit "C"', player: 1, type: 'char', pswap: 76, sswap: 44};
commands[13] = {desc: 'P1 Right Digit "d"', player: 1, type: 'char', pswap: 77, sswap: 45};
commands[14] = {desc: 'P1 Right Digit "E"', player: 1, type: 'char', pswap: 78, sswap: 46};
commands[15] = {desc: 'P1 Right Digit "F"', player: 1, type: 'char', pswap: 79, sswap: 47};
commands[16] = {desc: 'P1 Right Digit "G"', player: 1, type: 'char', pswap: 80, sswap: 48};
commands[17] = {desc: 'P1 Right Digit "H"', player: 1, type: 'char', pswap: 81, sswap: 49};
commands[18] = {desc: 'P1 Right Digit "I"', player: 1, type: 'char', pswap: 82, sswap: 50};
commands[19] = {desc: 'P1 Right Digit "J"', player: 1, type: 'char', pswap: 83, sswap: 51};
commands[20] = {desc: 'P1 Right Digit "k"', player: 1, type: 'char', pswap: 84, sswap: 52};
commands[21] = {desc: 'P1 Right Digit "L"', player: 1, type: 'char', pswap: 85, sswap: 53};
commands[22] = {desc: 'P1 Right Digit "n"', player: 1, type: 'char', pswap: 86, sswap: 54};
commands[23] = {desc: 'P1 Right Digit "o"', player: 1, type: 'char', pswap: 87, sswap: 55};
commands[24] = {desc: 'P1 Right Digit "P"', player: 1, type: 'char', pswap: 88, sswap: 56};
commands[25] = {desc: 'P1 Right Digit "q"', player: 1, type: 'char', pswap: 89, sswap: 57};
commands[26] = {desc: 'P1 Right Digit "r"', player: 1, type: 'char', pswap: 90, sswap: 58};
commands[27] = {desc: 'P1 Right Digit "T"', player: 1, type: 'char', pswap: 91, sswap: 59};
commands[28] = {desc: 'P1 Right Digit "U"', player: 1, type: 'char', pswap: 92, sswap: 60};
commands[29] = {desc: 'P1 Right Digit "v"', player: 1, type: 'char', pswap: 93, sswap: 61};
commands[30] = {desc: 'P1 Right Digit "y"', player: 1, type: 'char', pswap: 94, sswap: 62};
commands[31] = {desc: 'P1 Right Digit " "', player: 1, type: 'char', pswap: 95, sswap: 63};
commands[32] = {desc: 'P1 Left Digit "0"', player: 1, type: 'char', pswap: 96, sswap: 0};
commands[33] = {desc: 'P1 Left Digit "1"', player: 1, type: 'char', pswap: 97, sswap: 1};
commands[34] = {desc: 'P1 Left Digit "2"', player: 1, type: 'char', pswap: 98, sswap: 2};
commands[35] = {desc: 'P1 Left Digit "3"', player: 1, type: 'char', pswap: 99, sswap: 3};
commands[36] = {desc: 'P1 Left Digit "4"', player: 1, type: 'char', pswap: 100, sswap: 4};
commands[37] = {desc: 'P1 Left Digit "5"', player: 1, type: 'char', pswap: 101, sswap: 5};
commands[38] = {desc: 'P1 Left Digit "6"', player: 1, type: 'char', pswap: 102, sswap: 6};
commands[39] = {desc: 'P1 Left Digit "7"', player: 1, type: 'char', pswap: 103, sswap: 7};
commands[40] = {desc: 'P1 Left Digit "8"', player: 1, type: 'char', pswap: 104, sswap: 8};
commands[41] = {desc: 'P1 Left Digit "9"', player: 1, type: 'char', pswap: 105, sswap: 9};
commands[42] = {desc: 'P1 Left Digit "A"', player: 1, type: 'char', pswap: 106, sswap: 10};
commands[43] = {desc: 'P1 Left Digit "b"', player: 1, type: 'char', pswap: 107, sswap: 11};
commands[44] = {desc: 'P1 Left Digit "C"', player: 1, type: 'char', pswap: 108, sswap: 12};
commands[45] = {desc: 'P1 Left Digit "d"', player: 1, type: 'char', pswap: 109, sswap: 13};
commands[46] = {desc: 'P1 Left Digit "E"', player: 1, type: 'char', pswap: 110, sswap: 14};
commands[47] = {desc: 'P1 Left Digit "F"', player: 1, type: 'char', pswap: 111, sswap: 15};
commands[48] = {desc: 'P1 Left Digit "G"', player: 1, type: 'char', pswap: 112, sswap: 16};
commands[49] = {desc: 'P1 Left Digit "H"', player: 1, type: 'char', pswap: 113, sswap: 17};
commands[50] = {desc: 'P1 Left Digit "I"', player: 1, type: 'char', pswap: 114, sswap: 18};
commands[51] = {desc: 'P1 Left Digit "J"', player: 1, type: 'char', pswap: 115, sswap: 19};
commands[52] = {desc: 'P1 Left Digit "k"', player: 1, type: 'char', pswap: 116, sswap: 20};
commands[53] = {desc: 'P1 Left Digit "L"', player: 1, type: 'char', pswap: 117, sswap: 21};
commands[54] = {desc: 'P1 Left Digit "n"', player: 1, type: 'char', pswap: 118, sswap: 22};
commands[55] = {desc: 'P1 Left Digit "o"', player: 1, type: 'char', pswap: 119, sswap: 23};
commands[56] = {desc: 'P1 Left Digit "P"', player: 1, type: 'char', pswap: 120, sswap: 24};
commands[57] = {desc: 'P1 Left Digit "q"', player: 1, type: 'char', pswap: 121, sswap: 25};
commands[58] = {desc: 'P1 Left Digit "r"', player: 1, type: 'char', pswap: 122, sswap: 26};
commands[59] = {desc: 'P1 Left Digit "T"', player: 1, type: 'char', pswap: 123, sswap: 27};
commands[60] = {desc: 'P1 Left Digit "U"', player: 1, type: 'char', pswap: 124, sswap: 28};
commands[61] = {desc: 'P1 Left Digit "v"', player: 1, type: 'char', pswap: 125, sswap: 29};
commands[62] = {desc: 'P1 Left Digit "y"', player: 1, type: 'char', pswap: 126, sswap: 30};
commands[63] = {desc: 'P1 Left Digit " "', player: 1, type: 'char', pswap: 127, sswap: 31};
commands[64] = {desc: 'P2 Right Digit "0"', player: 2, type: 'char', pswap: 0, sswap: 96};
commands[65] = {desc: 'P2 Right Digit "1"', player: 2, type: 'char', pswap: 1, sswap: 97};
commands[66] = {desc: 'P2 Right Digit "2"', player: 2, type: 'char', pswap: 2, sswap: 98};
commands[67] = {desc: 'P2 Right Digit "3"', player: 2, type: 'char', pswap: 3, sswap: 99};
commands[68] = {desc: 'P2 Right Digit "4"', player: 2, type: 'char', pswap: 4, sswap: 100};
commands[69] = {desc: 'P2 Right Digit "5"', player: 2, type: 'char', pswap: 5, sswap: 101};
commands[70] = {desc: 'P2 Right Digit "6"', player: 2, type: 'char', pswap: 6, sswap: 102};
commands[71] = {desc: 'P2 Right Digit "7"', player: 2, type: 'char', pswap: 7, sswap: 103};
commands[72] = {desc: 'P2 Right Digit "8"', player: 2, type: 'char', pswap: 8, sswap: 104};
commands[73] = {desc: 'P2 Right Digit "9"', player: 2, type: 'char', pswap: 9, sswap: 105};
commands[74] = {desc: 'P2 Right Digit "A"', player: 2, type: 'char', pswap: 10, sswap: 106};
commands[75] = {desc: 'P2 Right Digit "b"', player: 2, type: 'char', pswap: 11, sswap: 107};
commands[76] = {desc: 'P2 Right Digit "C"', player: 2, type: 'char', pswap: 12, sswap: 108};
commands[77] = {desc: 'P2 Right Digit "d"', player: 2, type: 'char', pswap: 13, sswap: 109};
commands[78] = {desc: 'P2 Right Digit "E"', player: 2, type: 'char', pswap: 14, sswap: 110};
commands[79] = {desc: 'P2 Right Digit "F"', player: 2, type: 'char', pswap: 15, sswap: 111};
commands[80] = {desc: 'P2 Right Digit "G"', player: 2, type: 'char', pswap: 16, sswap: 112};
commands[81] = {desc: 'P2 Right Digit "H"', player: 2, type: 'char', pswap: 17, sswap: 113};
commands[82] = {desc: 'P2 Right Digit "I"', player: 2, type: 'char', pswap: 18, sswap: 114};
commands[83] = {desc: 'P2 Right Digit "J"', player: 2, type: 'char', pswap: 19, sswap: 115};
commands[84] = {desc: 'P2 Right Digit "k"', player: 2, type: 'char', pswap: 20, sswap: 116};
commands[85] = {desc: 'P2 Right Digit "L"', player: 2, type: 'char', pswap: 21, sswap: 117};
commands[86] = {desc: 'P2 Right Digit "n"', player: 2, type: 'char', pswap: 22, sswap: 118};
commands[87] = {desc: 'P2 Right Digit "o"', player: 2, type: 'char', pswap: 23, sswap: 119};
commands[88] = {desc: 'P2 Right Digit "P"', player: 2, type: 'char', pswap: 24, sswap: 120};
commands[89] = {desc: 'P2 Right Digit "q"', player: 2, type: 'char', pswap: 25, sswap: 121};
commands[90] = {desc: 'P2 Right Digit "r"', player: 2, type: 'char', pswap: 26, sswap: 122};
commands[91] = {desc: 'P2 Right Digit "T"', player: 2, type: 'char', pswap: 27, sswap: 123};
commands[92] = {desc: 'P2 Right Digit "U"', player: 2, type: 'char', pswap: 28, sswap: 124};
commands[93] = {desc: 'P2 Right Digit "v"', player: 2, type: 'char', pswap: 29, sswap: 125};
commands[94] = {desc: 'P2 Right Digit "y"', player: 2, type: 'char', pswap: 30, sswap: 126};
commands[95] = {desc: 'P2 Right Digit " "', player: 2, type: 'char', pswap: 31, sswap: 127};
commands[96] = {desc: 'P2 Left Digit "0"', player: 2, type: 'char', pswap: 32, sswap: 64};
commands[97] = {desc: 'P2 Left Digit "1"', player: 2, type: 'char', pswap: 33, sswap: 65};
commands[98] = {desc: 'P2 Left Digit "2"', player: 2, type: 'char', pswap: 34, sswap: 66};
commands[99] = {desc: 'P2 Left Digit "3"', player: 2, type: 'char', pswap: 35, sswap: 67};
commands[100] = {desc: 'P2 Left Digit "4"', player: 2, type: 'char', pswap: 36, sswap: 68};
commands[101] = {desc: 'P2 Left Digit "5"', player: 2, type: 'char', pswap: 37, sswap: 69};
commands[102] = {desc: 'P2 Left Digit "6"', player: 2, type: 'char', pswap: 38, sswap: 70};
commands[103] = {desc: 'P2 Left Digit "7"', player: 2, type: 'char', pswap: 39, sswap: 71};
commands[104] = {desc: 'P2 Left Digit "8"', player: 2, type: 'char', pswap: 40, sswap: 72};
commands[105] = {desc: 'P2 Left Digit "9"', player: 2, type: 'char', pswap: 41, sswap: 73};
commands[106] = {desc: 'P2 Left Digit "A"', player: 2, type: 'char', pswap: 42, sswap: 74};
commands[107] = {desc: 'P2 Left Digit "b"', player: 2, type: 'char', pswap: 43, sswap: 75};
commands[108] = {desc: 'P2 Left Digit "C"', player: 2, type: 'char', pswap: 44, sswap: 76};
commands[109] = {desc: 'P2 Left Digit "d"', player: 2, type: 'char', pswap: 45, sswap: 77};
commands[110] = {desc: 'P2 Left Digit "E"', player: 2, type: 'char', pswap: 46, sswap: 78};
commands[111] = {desc: 'P2 Left Digit "F"', player: 2, type: 'char', pswap: 47, sswap: 79};
commands[112] = {desc: 'P2 Left Digit "G"', player: 2, type: 'char', pswap: 48, sswap: 80};
commands[113] = {desc: 'P2 Left Digit "H"', player: 2, type: 'char', pswap: 49, sswap: 81};
commands[114] = {desc: 'P2 Left Digit "I"', player: 2, type: 'char', pswap: 50, sswap: 82};
commands[115] = {desc: 'P2 Left Digit "J"', player: 2, type: 'char', pswap: 51, sswap: 83};
commands[116] = {desc: 'P2 Left Digit "k"', player: 2, type: 'char', pswap: 52, sswap: 84};
commands[117] = {desc: 'P2 Left Digit "L"', player: 2, type: 'char', pswap: 53, sswap: 85};
commands[118] = {desc: 'P2 Left Digit "n"', player: 2, type: 'char', pswap: 54, sswap: 86};
commands[119] = {desc: 'P2 Left Digit "o"', player: 2, type: 'char', pswap: 55, sswap: 87};
commands[120] = {desc: 'P2 Left Digit "P"', player: 2, type: 'char', pswap: 56, sswap: 88};
commands[121] = {desc: 'P2 Left Digit "q"', player: 2, type: 'char', pswap: 57, sswap: 89};
commands[122] = {desc: 'P2 Left Digit "r"', player: 2, type: 'char', pswap: 58, sswap: 90};
commands[123] = {desc: 'P2 Left Digit "T"', player: 2, type: 'char', pswap: 59, sswap: 91};
commands[124] = {desc: 'P2 Left Digit "U"', player: 2, type: 'char', pswap: 60, sswap: 92};
commands[125] = {desc: 'P2 Left Digit "v"', player: 2, type: 'char', pswap: 61, sswap: 93};
commands[126] = {desc: 'P2 Left Digit "y"', player: 2, type: 'char', pswap: 62, sswap: 94};
commands[127] = {desc: 'P2 Left Digit " "', player: 2, type: 'char', pswap: 63, sswap: 95};
commands[128] = {desc: 'P1 Both Dots, P2 Both Dots', player: null, type: 'dots', pswap: 128, mirror: 128};
commands[129] = {desc: 'P1 Left Dot,  P2 Both Dots', player: null, type: 'dots', pswap: 132, mirror: 128};
commands[130] = {desc: 'P1 Right Dot, P2 Both Dots', player: null, type: 'dots', pswap: 136, mirror: 128};
commands[131] = {desc: 'P1 No Dots,   P2 Both Dots', player: null, type: 'dots', pswap: 140, mirror: 128};
commands[132] = {desc: 'P1 Both Dots, P2 Left Dot',  player: null, type: 'dots', pswap: 129, mirror: 128};
commands[133] = {desc: 'P1 Left Dot,  P2 Left Dot',  player: null, type: 'dots', pswap: 133, mirror: 133};
commands[134] = {desc: 'P1 Right Dot, P2 Left Dot',  player: null, type: 'dots', pswap: 137, mirror: 128};
commands[135] = {desc: 'P1 No Dots,   P2 Left Dot',  player: null, type: 'dots', pswap: 141, mirror: 133};
commands[136] = {desc: 'P1 Both Dots, P2 Right Dot', player: null, type: 'dots', pswap: 130, mirror: 128};
commands[137] = {desc: 'P1 Left Dot,  P2 Right Dot', player: null, type: 'dots', pswap: 134, mirror: 128};
commands[138] = {desc: 'P1 Right Dot, P2 Right Dot', player: null, type: 'dots', pswap: 138, mirror: 138};
commands[139] = {desc: 'P1 No Dots,   P2 Right Dot', player: null, type: 'dots', pswap: 142, mirror: 138};
commands[140] = {desc: 'P1 Both Dots, P2 No Dots',   player: null, type: 'dots', pswap: 131, mirror: 128};
commands[141] = {desc: 'P1 Left Dot,  P2 No Dots',   player: null, type: 'dots', pswap: 135, mirror: 133};
commands[142] = {desc: 'P1 Right Dot, P2 No Dots',   player: null, type: 'dots', pswap: 139, mirror: 138};
commands[143] = {desc: 'P1 No Dots,   P2 No Dots',   player: null, type: 'dots', pswap: 143, mirror: 143};
commands[144] = {desc: 'P1 Winner Lamp ON', player: 1, type: 'wl', pswap: 152};
commands[145] = {desc: 'P1 Winner Lamp Slow Flash', player: 1, type: 'wl', pswap: 153};
commands[146] = {desc: 'P1 Winner Lamp Med Flash', player: 1, type: 'wl', pswap: 154};
commands[147] = {desc: 'P1 Winner Lamp Fast Flash', player: 1, type: 'wl', pswap: 155};
commands[148] = {desc: 'P1 Winner Lamp Double Flash', player: 1, type: 'wl', pswap: 156};
commands[149] = {desc: 'P1 Winner Lamp Triple Flash', player: 1, type: 'wl', pswap: 157};
commands[150] = {desc: 'P1 Winner Lamp Quadruple Flash', player: 1, type: 'wl', pswap: 158};
commands[151] = {desc: 'P1 Winner Lamp OFF', player: 1, type: 'wl', pswap: 159};
commands[152] = {desc: 'P2 Winner Lamp ON', player: 2, type: 'wl', pswap: 144};
commands[153] = {desc: 'P2 Winner Lamp Slow Flash', player: 2, type: 'wl', pswap: 145};
commands[154] = {desc: 'P2 Winner Lamp Med Flash', player: 2, type: 'wl', pswap: 146};
commands[155] = {desc: 'P2 Winner Lamp Fast Flash', player: 2, type: 'wl', pswap: 147};
commands[156] = {desc: 'P2 Winner Lamp Double Flash', player: 2, type: 'wl', pswap: 148};
commands[157] = {desc: 'P2 Winner Lamp Triple Flash', player: 2, type: 'wl', pswap: 149};
commands[158] = {desc: 'P2 Winner Lamp Quadruple Flash', player: 2, type: 'wl', pswap: 150};
commands[159] = {desc: 'P2 Winner Lamp OFF', player: 2, type: 'wl', pswap: 151};
commands[160] = {desc: 'P1 "SEGA" Text Scroll ', player: 1, type: 'ani', pswap: 168};
commands[161] = {desc: 'P1 "Spinning Wheels" Animation ', player: 1, type: 'ani', pswap: 169};
commands[162] = {desc: 'P1 "The Wave" Animation ', player: 1, type: 'ani', pswap: 170};
commands[163] = {desc: 'P1 "Square Chase" Animation ', player: 1, type: 'ani', pswap: 171};
commands[164] = {desc: 'P1 "C Chase" Animation ', player: 1, type: 'ani', pswap: 172};
commands[165] = {desc: 'P1 "The Fountain" Animation ', player: 1, type: 'ani', pswap: 173};
commands[166] = {desc: 'P1 "The Snake" Animation ', player: 1, type: 'ani', pswap: 174};
commands[167] = {desc: 'P1 "Line Chase" Animation ', player: 1, type: 'ani', pswap: 175};
commands[168] = {desc: 'P2 "SEGA" Text Scroll ', player: 2, type: 'ani', pswap: 160};
commands[169] = {desc: 'P2 "Spinning Wheels" Animation ', player: 2, type: 'ani', pswap: 161};
commands[170] = {desc: 'P2 "The Wave" Animation ', player: 2, type: 'ani', pswap: 162};
commands[171] = {desc: 'P2 "Square Chase" Animation ', player: 2, type: 'ani', pswap: 163};
commands[172] = {desc: 'P2 "C Chase" Animation ', player: 2, type: 'ani', pswap: 164};
commands[173] = {desc: 'P2 "The Fountain" Animation ', player: 2, type: 'ani', pswap: 165};
commands[174] = {desc: 'P2 "The Snake" Animation ', player: 2, type: 'ani', pswap: 166};
commands[175] = {desc: 'P2 "Line Chase" Animation ', player: 2, type: 'ani', pswap: 167};
commands[176] = {desc: 'P1 Right Seg A ON', player: 1, type: 'seg', pswap: 208, sswap: 192};
commands[177] = {desc: 'P1 Right Seg B ON', player: 1, type: 'seg', pswap: 209, sswap: 193};
commands[178] = {desc: 'P1 Right Seg C ON', player: 1, type: 'seg', pswap: 210, sswap: 194};
commands[179] = {desc: 'P1 Right Seg D ON', player: 1, type: 'seg', pswap: 211, sswap: 195};
commands[180] = {desc: 'P1 Right Seg E ON', player: 1, type: 'seg', pswap: 212, sswap: 196};
commands[181] = {desc: 'P1 Right Seg F ON', player: 1, type: 'seg', pswap: 213, sswap: 197};
commands[182] = {desc: 'P1 Right Seg G ON', player: 1, type: 'seg', pswap: 214, sswap: 198};
commands[183] = {desc: 'P1 Right Dot ON', player: 1, type: 'seg', pswap: 215, sswap: 199};
commands[184] = {desc: 'P1 Right Seg A OFF', player: 1, type: 'seg', pswap: 216, sswap: 200};
commands[185] = {desc: 'P1 Right Seg B OFF', player: 1, type: 'seg', pswap: 217, sswap: 201};
commands[186] = {desc: 'P1 Right Seg C OFF', player: 1, type: 'seg', pswap: 218, sswap: 202};
commands[187] = {desc: 'P1 Right Seg D OFF', player: 1, type: 'seg', pswap: 219, sswap: 203};
commands[188] = {desc: 'P1 Right Seg E OFF', player: 1, type: 'seg', pswap: 220, sswap: 204};
commands[189] = {desc: 'P1 Right Seg F OFF', player: 1, type: 'seg', pswap: 221, sswap: 205};
commands[190] = {desc: 'P1 Right Seg G OFF', player: 1, type: 'seg', pswap: 222, sswap: 206};
commands[191] = {desc: 'P1 Right Dot OFF', player: 1, type: 'seg', pswap: 223, sswap: 207};
commands[192] = {desc: 'P1 Left Seg A ON', player: 1, type: 'seg', pswap: 224, sswap: 176};
commands[193] = {desc: 'P1 Left Seg B ON', player: 1, type: 'seg', pswap: 225, sswap: 177};
commands[194] = {desc: 'P1 Left Seg C ON', player: 1, type: 'seg', pswap: 226, sswap: 178};
commands[195] = {desc: 'P1 Left Seg D ON', player: 1, type: 'seg', pswap: 227, sswap: 179};
commands[196] = {desc: 'P1 Left Seg E ON', player: 1, type: 'seg', pswap: 228, sswap: 180};
commands[197] = {desc: 'P1 Left Seg F ON', player: 1, type: 'seg', pswap: 229, sswap: 181};
commands[198] = {desc: 'P1 Left Seg G ON', player: 1, type: 'seg', pswap: 230, sswap: 182};
commands[199] = {desc: 'P1 Left Dot ON', player: 1, type: 'seg', pswap: 231, sswap: 183};
commands[200] = {desc: 'P1 Left Seg A OFF', player: 1, type: 'seg', pswap: 232, sswap: 184};
commands[201] = {desc: 'P1 Left Seg B OFF', player: 1, type: 'seg', pswap: 233, sswap: 185};
commands[202] = {desc: 'P1 Left Seg C OFF', player: 1, type: 'seg', pswap: 234, sswap: 186};
commands[203] = {desc: 'P1 Left Seg D OFF', player: 1, type: 'seg', pswap: 235, sswap: 187};
commands[204] = {desc: 'P1 Left Seg E OFF', player: 1, type: 'seg', pswap: 236, sswap: 188};
commands[205] = {desc: 'P1 Left Seg F OFF', player: 1, type: 'seg', pswap: 237, sswap: 189};
commands[206] = {desc: 'P1 Left Seg G OFF', player: 1, type: 'seg', pswap: 238, sswap: 190};
commands[207] = {desc: 'P1 Left Dot OFF', player: 1, type: 'seg', pswap: 239, sswap: 191};
commands[208] = {desc: 'P2 Right Seg A ON', player: 2, type: 'seg', pswap: 176, sswap: 224};
commands[209] = {desc: 'P2 Right Seg B ON', player: 2, type: 'seg', pswap: 177, sswap: 225};
commands[210] = {desc: 'P2 Right Seg C ON', player: 2, type: 'seg', pswap: 178, sswap: 226};
commands[211] = {desc: 'P2 Right Seg D ON', player: 2, type: 'seg', pswap: 179, sswap: 227};
commands[212] = {desc: 'P2 Right Seg E ON', player: 2, type: 'seg', pswap: 180, sswap: 228};
commands[213] = {desc: 'P2 Right Seg F ON', player: 2, type: 'seg', pswap: 181, sswap: 229};
commands[214] = {desc: 'P2 Right Seg G ON', player: 2, type: 'seg', pswap: 182, sswap: 230};
commands[215] = {desc: 'P2 Right Dot ON', player: 2, type: 'seg', pswap: 183, sswap: 231};
commands[216] = {desc: 'P2 Right Seg A OFF', player: 2, type: 'seg', pswap: 184, sswap: 232};
commands[217] = {desc: 'P2 Right Seg B OFF', player: 2, type: 'seg', pswap: 185, sswap: 233};
commands[218] = {desc: 'P2 Right Seg C OFF', player: 2, type: 'seg', pswap: 186, sswap: 234};
commands[219] = {desc: 'P2 Right Seg D OFF', player: 2, type: 'seg', pswap: 187, sswap: 235};
commands[220] = {desc: 'P2 Right Seg E OFF', player: 2, type: 'seg', pswap: 188, sswap: 236};
commands[221] = {desc: 'P2 Right Seg F OFF', player: 2, type: 'seg', pswap: 189, sswap: 237};
commands[222] = {desc: 'P2 Right Seg G OFF', player: 2, type: 'seg', pswap: 190, sswap: 238};
commands[223] = {desc: 'P2 Right Dot OFF', player: 2, type: 'seg', pswap: 191, sswap: 239};
commands[224] = {desc: 'P2 Left Seg A ON', player: 2, type: 'seg', pswap: 192, sswap: 208};
commands[225] = {desc: 'P2 Left Seg B ON', player: 2, type: 'seg', pswap: 193, sswap: 209};
commands[226] = {desc: 'P2 Left Seg C ON', player: 2, type: 'seg', pswap: 194, sswap: 210};
commands[227] = {desc: 'P2 Left Seg D ON', player: 2, type: 'seg', pswap: 195, sswap: 211};
commands[228] = {desc: 'P2 Left Seg E ON', player: 2, type: 'seg', pswap: 196, sswap: 212};
commands[229] = {desc: 'P2 Left Seg F ON', player: 2, type: 'seg', pswap: 197, sswap: 213};
commands[230] = {desc: 'P2 Left Seg G ON', player: 2, type: 'seg', pswap: 198, sswap: 214};
commands[231] = {desc: 'P2 Left Dot ON', player: 2, type: 'seg', pswap: 199, sswap: 215};
commands[232] = {desc: 'P2 Left Seg A OFF', player: 2, type: 'seg', pswap: 200, sswap: 216};
commands[233] = {desc: 'P2 Left Seg B OFF', player: 2, type: 'seg', pswap: 201, sswap: 217};
commands[234] = {desc: 'P2 Left Seg C OFF', player: 2, type: 'seg', pswap: 202, sswap: 218};
commands[235] = {desc: 'P2 Left Seg D OFF', player: 2, type: 'seg', pswap: 203, sswap: 219};
commands[236] = {desc: 'P2 Left Seg E OFF', player: 2, type: 'seg', pswap: 204, sswap: 220};
commands[237] = {desc: 'P2 Left Seg F OFF', player: 2, type: 'seg', pswap: 205, sswap: 221};
commands[238] = {desc: 'P2 Left Seg G OFF', player: 2, type: 'seg', pswap: 206, sswap: 222};
commands[239] = {desc: 'P2 Left Dot OFF', player: 2, type: 'seg', pswap: 207, sswap: 223};
commands[240] = {desc: 'P1 "P1" Demo Loop', player: 1, type: 'ani', pswap: 249};
commands[241] = {desc: 'P1 "P2" Demo Loop', player: 1, type: 'ani', pswap: 248};
commands[242] = {desc: 'P1 "vErSUS CITy" Text Scroll', player: 1, type: 'ani', pswap: 250};
commands[248] = {desc: 'P2 "P1" Demo Loop', player: 2, type: 'ani', pswap: 241};
commands[249] = {desc: 'P2 "P2" Demo Loop', player: 2, type: 'ani', pswap: 240};
commands[250] = {desc: 'P2 "vErSUS CITy" Text Scroll', player: 2, type: 'ani', pswap: 242};
commands[255] = {desc: 'DO NOTHING', player: null, type: 'ani', pswap: 255, mirror: 255};

/* The bb_text dictionary below is used to determine the commands to be used when converting
   plain text to billboard commands. 
   
   All commands are based on the player 1 right digits
   to get the commands for other digit you can retrieve the corrosponding "sswap" value in 
   the commands library above. similarly the pswap value can be used to retrieve the commands 
   for the other player.
   
   Some letters or symbols do not have descrete commands so 2 or more commands must be issued
   to "construct" the appropriate display output. In these cases it's recommended that as few 
   commands are issued as possible to keep the speed as high as possible. also command sequences
   that avoid using the "segment off" commands are ideal as illuminating a segment and then 
   deactivating it could potentionally cause flickers in the resulting output.
*/
var bb_text = {};
bb_text['0'] = [0];
bb_text['1'] = [1];
bb_text['2'] = [2];
bb_text['3'] = [3];
bb_text['4'] = [4];
bb_text['5'] = [5];
bb_text['6'] = [6];
bb_text['7'] = [7];
bb_text['8'] = [8];
bb_text['9'] = [9];
bb_text['a'] = [10];
bb_text['b'] = [11];
bb_text['c'] = [12];
bb_text['d'] = [13];
bb_text['e'] = [14];
bb_text['f'] = [15];
bb_text['g'] = [16];
bb_text['h'] = [17];
bb_text['i'] = [18];
bb_text['j'] = [19];
bb_text['k'] = [20];
bb_text['l'] = [21];
bb_text['m'] = [29,187,176]; //display a v, turn off segment d, turn on segment a
bb_text['n'] = [22];
bb_text['o'] = [23];
bb_text['p'] = [24];
bb_text['q'] = [25];
bb_text['r'] = [26];
bb_text['s'] = [5]; //display a 5
bb_text['t'] = [27];
bb_text['u'] = [28];
bb_text['v'] = [29];
bb_text['w'] = [28,188,186]; //display a U, turn off segment e, turn off segment c
bb_text['x'] = [17]; //display an H
bb_text['y'] = [30];
bb_text['z'] = [2]; //display a 2
bb_text[' '] = [31];
bb_text['-'] = [31,182]; //clear display, turn on segment g
bb_text['_'] = [31,179]; //clear display, turn on segment d
bb_text['='] = [31,182,179]; //clear display, turn on segment g, turn on segment d
bb_text['^'] = [31,176]; //clear display, turn on segment a
bb_text['*'] = [24,188]; //display a P, turn off segment e
bb_text['/'] = [26,177]; //display an r, turn on segment b

//letters numbers and spaces are supported 
//in addition to the following special characters : .-_=^*/
//any other characters will be ignored